languageCode = "en-us"
title = "MINTS Biometrics Dashboard 3.0"
disableKinds = ["sitemap", "RSS"]
theme = "hugo-webslides"
themesDir = "themes"
tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  description = "UTD MINTS Biometrics Dashboard 3.0"
  author = "Madhav Mehta (madhavmehta1)"

[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
